### ISSUE TITLE
Enhanced privacy : Drop report-uri.com telemetric

### ISSUE THREAD

**Issue by 1000i100** [hedgedoc/hedgedoc#1026]
**Which part of the project should be enhanced?**
Privacy & Telemetry.

**Is your enhancement request related to a problem? Please describe.**
HackMD was Gafam dependant. HedgeDoc do better, but still share data with external european commercial operator, and without user consent.

**Describe the solution you'd like**
Switch to FOSS self-hostable solution if you want to keep telemetry.

Allow any hedgedoc host to disable telemetry with a simple boolean to change in config. (I have not checked, perhapse it allready possible).

**Describe alternatives you've considered**
https://matomo.org/ is FOSS self-hostable and respect DO_NOT_TRACK if set by the user.

**Additional context**

My internet dream is clean from trackers and surveillance capitalism with privacy by design FOSS everywhere.

Thank you for your awsome work on HedgeDoc !

**Comment by 1000i100** [comment]
Related : #923

**Comment by davidmehren** [comment]
I'm not sure what you want us to do here. There is no telemetry included in HedgeDoc by default. A server admin might configure [a CSP report URI](https://docs.hedgedoc.org/configuration/#web-security-aspects) (note that `CMD_CSP_REPORTURI` is `undefined` by default), but that you must directly discuss with them.

**Comment by SISheogorath** [comment]
On a more technical note: Report-URI is used to detect CSP violations. This is helpful to ensure that the application is working properly and CSPs are not too strict as well as monitoring situations where notes might be abused for attacks on users.

As @davidmehren already mentioned, this is up to the instance admin and there is no default to report-uri.com. 

The suggested alternative, matomo, is not at all an alternative, because it focuses in user tracking instead of CSP monitoring, which is a very different kind of thing.

In best case, when no CSP violation takes place, report-uri.com will not even be contacted. The main source of violations I see on the demo instance, where we actually use report-uri.com to make sure new versions of hedgedoc have well-working CSPs, are from browser extensions, who are not properly adding their own injections into the CSP of websites they operate on.

If you can suggest a self-hosted alternative to report-URI that gets the same job done, I would love to know, because so far, I couldn't findvone, except of an CSP-to-email tool, which would bombard me with hundreds of emails a week thanks to browser plugins I'm can't and won't fix.

**Comment by 1000i100** [comment]
Ok, so my concern is about the demo instance, i will investigate more about report-uri alternative and when it is or not contacted and how web-extension handle it.

Thanks for your message.
