### ISSUE TITLE
Delete associated uploads when deleting a note

### ISSUE THREAD

**Issue by davidmehren** [hedgedoc/hedgedoc#1065]
**Describe the solution you'd like**
By default, when deleting a note, all associated uploads should be deleted.
The APIs should also provide an optional parameter to skip the deletion process.

**Additional context**
This implements an aspect of documentation merged in #1033

**Comment by DerMolly** [comment]
Should the body contain something like
```
{
    deleteImages: true
}
```
or rather
```
{
    keepImages: false
}
```
?

**Comment by SISheogorath** [comment]
I think `deleteImages: true` sounds more like something I would expect from an API. If I send a request "delete note", I wouldn't expect that I would need to specify that I want to keep the pictures around.

**Comment by davidmehren** [comment]
IMO, the default behaviour should be to delete, as this is also the safer way with respect to data minimization. I therefore wrote
> The APIs should also provide an optional parameter to skip the deletion process.

which would result in an optional `keepImages`.

**Comment by davidmehren** [comment]
I think we call uploads "media", so actually `keepMedia` would probably be more consistent.

**Comment by DerMolly** [comment]
Good point

**Comment by SISheogorath** [comment]
For the client implementation I see this making complete sense, but for an API interface, not really. Because we have a /media/ API namespace which handles media data. It's a useful move to simplify handling by adding a `cascade: true` in there, but doing this by default as an API sounds rather odd to me and like a namespace violation.

It basically means, I have to in detail study the documentation of the API carefully before I can use it, without any unexpected side-effects i.e. I delete a note here and media disappears over there. And right now, I couldn't recall any API that would delete orthogonal data by default 🤔
