### ISSUE TITLE
The "day view" mode for the code editor is not available.

### ISSUE THREAD

**Issue by ChristianLaforest** [hedgedoc/hedgedoc#1103]
Hello. 

I am new in Hedge doc. Thank you for your work! However, in the main document "Features", it is mentioned:
"The editor view, which is in night mode by default, can also be toggled between night and day view using the the little sun."

This feature (and its "little sun") are not available. The editor code part is in dark mode, I cannot convert it in day mode. 
For information, my computer in a Mac Book pro (2012), Catalina. I tried with safari and Firefox. Is it a bug?

Thank you for your help. 

**Please use [the community forum](https://community.hedgedoc.org) to ask questions!**

**Comment by davidmehren** [comment]
The "little sun" should be located in the bottom toolbar of the editor:
![image](https://user-images.githubusercontent.com/5023650/113515408-9694a100-9574-11eb-85e0-ea97273786cb.png)

**Comment by ChristianLaforest** [comment]
@davidmehren 
Yes, it is! Thank you! 
I could not see it because of the too strong contrat on my screen. 
The day mode is much confortable for me. Thanks again.

**Comment by alice-telescoop** [comment]
I came here because I could not find it either. I only saw it when it was hovered. I suggest that you make it more visible

**Comment by DerMolly** [comment]
Hey @alice-telescoop,

thank you for your suggestion and welcome to the community.

Two things:
1. This issue is closed for a long time now, so in the future it would be better if you open up a new issue and link this issue in there. I know this is a bit more work, but reviving a super old topic is not the way to go.
2. As we state in the README HedgeDoc 1 is in maintaince mode, as we currently try to finish HedgeDoc 2. So we won't fix this. Maybe you want to look at https://hedgedoc.dev for a alpha demo of HedgeDoc 2. I think we don't have that problem there, but please feel free to open a new issue if everything else comes up.

**Comment by alice-telescoop** [comment]
Ok, thanks for your quick response.
Sorry for posting in the wrong place, I thought that duplicating subjects would be "wrost" than reviving old issues, but I now understand it is the contrary here.

I completely understand your answer did not know about the roadmap so I understand that my suggestion is not relevant in this context.

Good luck with HedgeDoc 2 then :)
