### ISSUE TITLE
DevTools failed to load SourceMap: Could not load content for mermaid.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

### ISSUE THREAD

**Issue by WithGJR** [hedgedoc/hedgedoc#1110]
**Description**

The issue is the same as [#289 ](https://github.com/hedgedoc/hedgedoc/issues/289)

I created a new issue because I think this problem needs to be solved.

Think about a situation like this: 
1. FreeURL mode is enabled.
2. You visit any random note's page.
3. And now a new note called mermaid.min.js.map being created.

The problem comes from the line 373 of the webpack.common.js file:
`mermaid: path.join(__dirname, 'node_modules/mermaid/dist/mermaid.min.js'),`

The content of this file has a SourceMap Directive included.

One solution to this problem might be: always use the CDN link for the mermaid.js ?

**To Reproduce**
1. Set the configuration:  `useSSL: false`
2. Open your browser and go to the page for any one of your notes. 
3. Open your Chrome's DevTool, and you will see this error.

You can see the problem happened on the official demo server as well.

**Your Setup (please complete the following information):**
 - HedgeDoc version: 1.7.2

**Comment by ErikMichelson** [comment]
With FreeURL mode I can confirm the creation of a note with the alias "mermaid.min.js.map". However, this shouldn't hurt anyone since the URL will always return HTML content that cannot be parsed as a source map.
Version 2.0 won't have this issue anymore, but if you're really concerned about this, you could add "mermaid.min.js.map" to the list of forbidden note-ids (see [docs](https://docs.hedgedoc.org/configuration/#hedgedoc-basics)).

The demo instance by the way does not show this problem as FreeURL mode is disabled there. The request for https://demo.hedgedoc.org/mermaid.min.js.map just returns a 404.

**Comment by davidmehren** [comment]
This can't be solved easily, as both `mermaid.min.js` and `mermaid.js` in the `mermaid` NPM package have  references to a `sourceMappingURL`. As this is mostly a cosmetic issue, we will not fix this in 1.x.
