### ISSUE TITLE
Evaluate type of primary columns

### ISSUE THREAD

**Issue by InnayTool** [hedgedoc/hedgedoc#1292]
**Which part of the project should be enhanced?**
Primary columns of all tables in the database

**Is your enhancement request related to a problem? Please describe.**
The primary columns are inconsistent by now.

**Describe the solution you'd like**
Choose number or UUID for primary columns.

**Comment by SISheogorath** [comment]
I just spend a few minutes on researching how well or unwell UUID types work in postgresql. The result seems to be that inserts can see a performance hit, due to reordering the index btree. But according to the few places I read, it's basically ignorable unless one builds a high-performance application. Otherwise, there is nothing else speaking against UUIDs, performance-wise.

Now let's look into meaning: Currently at least notes are identified by UUIDs and will be identified by UUIDs in the future. Therefore whether we like it or not, UUIDs will be part of all our requests for notes. In general it has turned out to be a good practice to keep UUIDs for basically all objects that can be requested through an API to prevent enumerations.

If we add a numerical ID for objects, it'll denormalise the form since the id and the UUID have the same information value. At the same time, since there will be indexes on the UUID fields either way, we also get the performance penalty for all objects that have UUIDs and can be queried.

All in all, I don't see much value in using anything else than UUIDs as primary keys for all exposed objects. Therefore, if we want to unify the primary keys, then UUIDs it is for me.

**Comment by davidmehren** [comment]
>  Currently at least notes are identified by UUIDs and will be identified by UUIDs in the future

We try to not leak IDs from the database into the API. In case of UUIDs for notes, we discovered early on that UUIDs generated by databases are not cryptographically random and therefore decided to add a separate `publicId` (see also [here](https://github.com/hedgedoc/hedgedoc/issues/864#issuecomment-777739970)).

The type of primary key used in the database *should* be completely opaque to the consumers of the REST-API, because they have a separate public identifier or are not queryable by an ID.

**Comment by SISheogorath** [comment]
> The type of primary key used in the database should be completely opaque to the consumers of the REST-API, because they have a separate public identifier or are not queryable by an ID.

Technically it is, yes. But by what identifier do you want to let people query notes from the API? You can turn it as you want, you'll end up with the API IDs in the database (who generates them is a question on its own), and you'll have an index on them, resulting in the same performance impact on inserts whether you use them as primary key or not.

**Comment by InnayTool** [comment]
We decided to use integer ids because there is no benefit in using UUIDs if we don't want to send them over the wire and UUIDs are only overhead for handling in application and database.
