### ISSUE TITLE
no link between slides

### ISSUE THREAD

**Issue by oupala** [hedgedoc/hedgedoc#1476]
**Description**

When presenting slides, the feature to create links between slides does not work.

**To Reproduce**

1. Go to demo slides (of the demo instance)
2. Go to [page 18](https://demo.hedgedoc.org/p/slide-example#/17)
3. Click on link "like this"
4. See that the browser is redirected to home page

**Expected behavior**

The link should lead to slide `1/3`.

**Logs**

n/a

**Config**

n/a

**Setup:**

 - demo instance

**Additional context**

n/a

**Comment by mrdrogdrog** [comment]
I know this issue. We already discussed about this but I can't remember when :thinking:
Anyway. I still know the results:

Reveal.js uses relative URLs to link slides. But HedgeDoc sets a base url to handle subdirectories and domains in a `base` meta tag which expands relative URLs to absolute. The resulting URL is broken because it points to nowhere.
We can't fix this without redoing a lot of old ugly code.
There is a workaround: Instead of `#3/2/1` use `p/NOTE_ID#3/2/1`.
I'm going to create PR that changes the slide example code.

**Comment by mrdrogdrog** [comment]
We found a way to fix this issue. At least I hope it doesn't break more stuff than it fixes.

**Comment by oupala** [comment]
A workaround and a fix, marvellous !

**Comment by ErikMichelson** [comment]
Fixed in #1479
