### ISSUE TITLE
grouping/folder/subpages

### ISSUE THREAD

**Issue by mzechmeister** [hedgedoc/hedgedoc#1555]
I would to organise/structure long documents by breaking them down into smaller ones.
How can this be organised?
Could there be subpages (like in wiki subpages) or a grouping in project folders and subfolders?

(Actually, it goes requesting for a speedy/on-the-fly wiki system.)

**Comment by davidmehren** [comment]
Hi!

The introduction of folders [is planned for 2.0](https://github.com/hedgedoc/hedgedoc/issues/1002#issuecomment-792049138). You can also have a look at the existing issues with the [note organization label](https://github.com/hedgedoc/hedgedoc/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A%22feature%3Anote+organization%22), where various other aspects are discussed.

In the future, before opening new issues, please search the existing ones first and also use the provided template. Otherwise, you make life needlessly hard for us maintainers :)

**Comment by mzechmeister** [comment]
Thanks. Looking forward for 2.0!
