### ISSUE TITLE
Hide scrollbar in slide mode

### ISSUE THREAD

**Issue by ndaidong** [hedgedoc/hedgedoc#1636]
Hello,

Scrollbar should not appear in slide mode. 
The "container" class is being defined to `overflow-y: scroll`. But it should be `hidden`.

Could you share your point of view?

![Screenshot from 2021-09-15 13-18-39](https://user-images.githubusercontent.com/1809619/133381053-3bf1d676-efe7-48d1-8782-4ae84e583ae9.png)

Thank you,

**Comment by mrdrogdrog** [comment]
Hello, 

Thanks for your issue.

First of all: please use the issue template we provide. It helps us a lot.

This scrollbar is intended because below are some additional information and links. [We don't plan to change that for HedgeDoc 1.x](https://github.com/hedgedoc/hedgedoc/blob/develop/README.md#state-of-the-project). HedgeDoc 2.0 will come with an improved slide mode.
