### ISSUE TITLE
Ensure consistent behaviour of entity `create` methods

### ISSUE THREAD

**Issue by davidmehren** [hedgedoc/hedgedoc#1641]
**Describe the solution you'd like**
The `create` methods of our entities currently have very inconsistent parameters.
They should always only require the non-optional properties of the corresponding entity and no optional parameters.

They should also either return a complete and fully useable instance or return a `Pick` type.

**Describe alternatives you've considered**
Keep the current inconsistencies.

**Additional context**

**Comment by DerMolly** [comment]
As I'm currently working on this, I noticed that both `session.entity.ts` and `tag.entity.ts` currently don't have any `create` methods  at all. Should they get some?

Currently session are created here https://github.com/hedgedoc/hedgedoc/blob/develop/src/utils/session.ts#L33-L37 and no `create` method is needed. 

Tags are currently not created, because we don't parse the yaml frontmatter of notes currently.

So I guess I'll leave it like it is know and we'll see how it goes from there.
