### ISSUE TITLE
Private API: Posting new history entries results in error

### ISSUE THREAD

**Issue by ErikMichelson** [hedgedoc/hedgedoc#1923]
### Description

Uploading history entries to the server fails.

### Steps to reproduce

1. Use the frontend with the backend and click the "Sync complete history to server"-button or do manually a POST to `/api/private/me/history`.
2. The backend will throw an error `history is not iterable`.

Example payload used (verified to match the HistoryImportDto type):
```json
[{"pinStatus":false,"lastVisited":"2021-12-02T21:48:43.794+01:00","note":"features"},{"pinStatus":false,"lastVisited":"2021-12-18T21:14:12.373Z","note":"test"},{"pinStatus":false,"lastVisited":"2021-12-18T21:09:12.000Z","note":"test3"},{"pinStatus":false,"lastVisited":"2021-12-18T21:09:12.000Z","note":"test2"}]
```

### Expected behaviour

The import succeeds.

### Logs

```shell
12/19/2021, 6:02:53 PM [HedgeDoc.ExceptionsHandler()] history is not iterable
TypeError: history is not iterable
    at [/home/erik/projects/hedgedoc-2/src/history/history.service.ts:159:34](https://github.com/hedgedoc/hedgedoc/blob/develop/src/history/history.service.ts#L159)
```

### Your Setup

- React-Client: branch `backend-connection`
- NodeJS version: 16.9.1
- HedgeDoc version: develop

**Comment by davidmehren** [comment]
This will be fixed by https://github.com/hedgedoc/hedgedoc/pull/2151

`@Body('history') history: HistoryEntryImportDto[]` expects a list of `HistoryEntryImportDto`s in the `history` property of the body.
This was confusing and could not be validated by `class-validator`, so was replaced by the new `HistoryEntryImportListDto` in [`ae37144` (#2151)](https://github.com/hedgedoc/hedgedoc/pull/2151/commits/ae37144a57a810a794afc359425ec5341b92c296)

**Comment by davidmehren** [comment]
To be more specific: The *500 error* will be fixed and turned into a proper validation error, you will also have to fix the frontend to send the expected JSON ;)
