### ISSUE TITLE
We should not return Bad Request when an alias is already in use

### ISSUE THREAD

**Issue by davidmehren** [hedgedoc/hedgedoc#1983]
### Which part of the project should be enhanced?

Both APIs

### Is your enhancement request related to a problem? Please describe.

Both the public and the private API return 400 Bad Request, when an alias is already used. This is a very generic error code.

### Describe the solution you'd like

The APIs should return 409 Conflict instead.

### Describe alternatives you've considered

Not changing the API.

**Comment by DerMolly** [comment]
I reworked the error mapping in https://github.com/hedgedoc/hedgedoc/pull/2037 and had a look just know. I think we could map AlreadyInDBError always to ConflictException, because that's basically what the error states. Here is something that conflicts with your request. I'll add this to the PR, if you agree @davidmehren.

**Comment by davidmehren** [comment]
Great idea!

I only had a brief look at the code, but `Conflict` should make sense everywhere `AlreadyInDBError` is thrown.
