### ISSUE TITLE
Can't paste (context menu) or use cursor placement pad on Firefox, iOS

### ISSUE THREAD

**Issue by ethereal-engineer** [hedgedoc/hedgedoc#2081]
### Description

As per description

### Steps to reproduce

1. On an iPhone, copy some text to clipboard
2. Open Hedgedoc in Firefox
3. Sign in
4. Create a new document
5. Type a heading
6. Press and hold in the document body to trigger a paste context menu
7. It never shows
8. Press and hold the spacebar to activate the cursor placement pad
9. The cursor appears outside of the document and cannot be moved within the document

### Expected behaviour

1. A working paste menu
2. A working cursor placement pad

### Config

```shell
Self-hosting HedgeDoc using Docker, behind an nginx reverse proxy, authenticated by Authelia
```

### Your Setup

- Host OS: Ubuntu 20.04
- HedgeDoc Docker Image Version: 1.9.2
- Firefox Version:  Daylight 96.0 (7403)
- iOS Version: 15.2.1

### Additional context

 I know this is two bugs but I'm giving you what I've got time to write :P :)

**Comment by mrdrogdrog** [comment]
This issue is already known. It's an upstream bug of the used editor (CodeMirror 5) which has only poor support for mobile browsers. There is nothing we can do here.
Luckily the mobile browser support has been improved in CodeMirror 6 [which will be included in HedgeDoc 2](https://GitHub.com/HedgeDoc/react-client/pulls/1787) but won't be backported to HedgeDoc 1.

**Comment by davidmehren** [comment]
Closing as won't fix for 1.x.

**Comment by ethereal-engineer** [comment]
Sweet!

Adam

**Comment by solarkraft** [comment]
I know this isn't exactly the most productive comment, but this is a real issue making HedgeDoc effectively close to unusable on iOS :(

Are there any workarounds that can be done individually or in the code?

It'd be such a bummer to have the rest of the app so nicely mobile optimized but then not support text editing on iOS ...

**Comment by mrdrogdrog** [comment]
We will not backport CodeMirror 6 into HedgeDoc 1. 
- The effort is huge because the code mirror 6 API is completely different
- it is unpredictable what will break because the HD1 code base is a horrible mess and untested
- we would have to reimplement every custom plugin that is not already included in HedgeDoc 2. E.g. the realtime communication is different between HD1 and HD2. Therefore we would have to reimplement the editor plugin of the realtime communication of HD1 for CM6
- not all vendored plugins that are currently available in cm5 exist for cm6, like the vim mode. This would be considered as breaking change.

I'm sorry to say this, but sadly you need to wait for HD2 if you want HedgeDoc with CodeMirror 6.
