### ISSUE TITLE
Unable to use <? in input

### ISSUE THREAD

**Issue by joho1968** [hedgedoc/hedgedoc#2789]
### Description

It seems like <? somehow is recognized as special sequence, why?

### Steps to reproduce

1. Start a new document
2. Type <, followed by ?, and both characters disappear
3. I tried adding a code tag around the text, but it's still not rendered correctly

`````
This is what the input was/is:

# So, the title goes here? :blush: 
What happens then?
And now?
And then?

```<?php
  echo "What is this?";
?>
```
`````

If I put the <?php tag on a new line, it renders correctly.

### Expected behaviour

I would have expected it to render as "code" and properly display <?php, and not hide the entire line.

### Your Setup

This is on the demo page https://demo.hedgedoc.org

**Comment by mrdrogdrog** [comment]
My guess: The markdown parser tries to parse this input as HTML.

Using a code block works.
![image](https://user-images.githubusercontent.com/6124140/198120378-f564cf5d-78d6-4ea4-bdfc-855410f0d38d.png)

Keep in mind that you can't start your code directly after the 3 backticks because this line is used to determine the highlighting language.

**Comment by joho1968** [comment]
Fair enough. I was just a bit surprised. But you're right, it's probably the expected behavior.
