### ISSUE TITLE
Restructure the features page

### ISSUE THREAD

**Issue by DerMolly** [hedgedoc/hedgedoc#2880]
I noticed while developing the react-client that there are many unprecise or even missing descriptions of the `feature.md` file. I thought if we maybe should move the file to the react-client repo, but since these files should primarily live in the backend, that seemed to be a bad idea. But maybe we should scrap the old file and write a complete new file. With a better structure (for my tasting the current file jumps all over the place in terms of topics) and a more complete list of feature. What do you think?

**Comment by ErikMichelson** [comment]
More than 2 years have passed since the last comment here.

In the meanwhile, we have added the **Cheatsheet** popup that replaces the help dialog and contains every syntax available in HedgeDoc. The cheatsheet is translated via usual translations. By being directly connected to the Markdown-Extensions, adding or updating content is very straight forward and avoids the problems of having a "special" note.

For listing HedgeDoc's capabilities we decided to showcase them in the official docs. This is tracked in #3655.

I'd therefore vote for dropping the concept of a "features" page completely. Currently, HD2 does not contain any code for the features page, therefore everything should be done by closing this issue.

What do you think, @hedgedoc/backend, @hedgedoc/frontend?

**Comment by ErikMichelson** [comment]
Closed for the reasons mentioned above.
