### ISSUE TITLE
Set `lang` attribute of root html element, editor container and render page properly

### ISSUE THREAD

**Issue by davidmehren** [hedgedoc/hedgedoc#2885]
Since hedgedoc/hedgedoc#437 we use the `lang` metadata attribute to set the corresponding HTML attribute.
This fix should be included in 2.0.

**Comment by DerMolly** [comment]
First of all we should use the current language of i18next for everything expect the editor, presentation and read-only view, where we should use the language setup in the frontmatter (which defaults to 'en' if nothing is provided).
This can be done with a `_document.tsx` file in the page folder (see https://nextjs.org/docs/pages/building-your-application/routing/custom-document) which should probably also additionally handle the stuff we currently do in `_app`.
Because of that, this issue is blocked by #4155

**Comment by mrdrogdrog** [comment]
Fixed by #4155
