### ISSUE TITLE
Sync local file with hedgedoc document (bi-directional)

### ISSUE THREAD

**Issue by distbit0** [hedgedoc/hedgedoc#3151]
### Is your feature request related to a problem? Please describe.

I host all of my documents locally in a folder of nested markdown files.

This is fine as long as I am the only one editing them. However if I want to share them with others, at the moment I have to paste their contents into a gist or a hedgedoc document, and share it with others by sending them a link to it.

This however does not allow other people to edit these documents without me manually copying and pasting their changes every time they make an edit, in order to keep my version in sync. 

### Describe the solution you'd like

I would like to be able to keep a local markdown file in sync with a certain hedgedoc document so that I can send someone a link to said hedgedoc document and allow them to edit it while keeping my local copy in sync.

This would be extremely useful as it would allow me to effectively achieve the same collaborative editing that is possible with google docs while still being able to edit of my markdown files locally, and without relying on a centralised cloud provider (I plan on self-hosting hedgedoc).

### Describe alternatives you've considered

- using etherpad (could not find any sync tools)
- using gists (does not support collaborative editing)
- using a git repository (requires other party to use git in order to edit doc, and doesn't allow for sharing only a single document to someone else without sharing entire repository/folder of docs, which is a significant privacy problem)
- using a cloud storage sync tool such as google drive (google drive doesn't have any inbuilt support for editing text files, and I do not want google to have access to my documents)

**Comment by DerMolly** [comment]
Hey @distbit0,

You probably could build something along the lines of what you want with the current CLI and it should only get better with the API we plan to include in HedgeDoc 2.0 when that is released. But afaik there is currently no tool to do this out of the box and you would need to build something for yourself.

If you happen to build something, I think we would be more than happy to link to your (hopefully open source) project from our documentation / website. 

I don't think this is something we offically want to support either (built it into the core of HedgeDoc), because by the very design of HedgeDoc it relies on markdown as the format, but is backed by a database and not markdown files. Because of that I'll mark this issue as closed. This is not intended to disregard your request, but just keep the open issues tightly associated with what needs to be done, designed or discussed for the core application.

**Comment by distbit0** [comment]
Thank you very much for the response, and totally understand if you'd prefer not to include this as a core feature.

By any chance could you refer me to any articles etc. which would point me in the right direction re: how to do this?
What I am least sure about is how to manage simultaneous edits of the local and remote file, and whether I can use some crdt mechanism built into hedgedoc for this or if I should create my own conflict resolution mechanism.

Many thx @DerMolly

**Comment by DerMolly** [comment]
Hey @distbit0,

sorry for the delay.

HedgeDoc 1 currently uses OT. The communication works via websocket, but is not really meant to be used by external tools (we won't stop you, but we won't keep an eye out for third party software and if we want to change something there we will). 
HedgeDoc 2 will use CRDTs, but the communication is also not part of the public api, so the same rules apply.

My best suggestion would be to use the CLI to replace the pad with an updated version or download the current version and replace your local version.
I know this is not as live as you want it to be, but that's what we offer / will offer for save consumption by third party tools.
