### ISSUE TITLE
Validate YAML frontmatter

### ISSUE THREAD

**Issue by mrdrogdrog** [hedgedoc/hedgedoc#3273]
### Which part of the project should be enhanced?

Frontend Frontmatter Parser

### Is your enhancement request related to a problem? Please describe.

Right now we just parse the YAML frontmatter and type cast it. This could lead to problems and possible security issues if users e.g. insert a list in the title field. 

### Describe the solution you'd like

Use a scheme validator like JOI to validate this external user input.

**Comment by hsedr** [comment]
Hey @mrdrogdrog,

we are a group of students who want to contribute to this project. This issue seems like an interesting starting point, but we need further clarification in order to understand your goal here. 

As of now we understand that the `load`-Function, which is used to parse the raw frontmatter into a an Object, poses a security issue, as nested JS-Scripts could be executed while parsing it.
So the goal here should be to avoid this function and instead use the JOI-validator?

Are we on the right track here, or did we miss something? Further informationen would be very appreciated.

best regards

**Comment by mrdrogdrog** [comment]
Hello,

almost right. The yaml load function doesn't execute parsed code and it also doesn't produce functions in the resulting object. The problem here isn't arbitrary code execution but just type safety.
Because of the used types our code expects e.g. the title to be a string. But if someone writes a frontmatter where the title is a list of numbers then this list is passed to the processing code and at some point it might crash.

So yes, a JOI validation would be nice.

**Comment by mrdrogdrog** [comment]
@hsedr Are you still working on this?

**Comment by hsedr** [comment]
Hi, yes we are working on it. What deadline should we retain?

**Comment by mrdrogdrog** [comment]
Already solved by #4107
