### ISSUE TITLE
Unable to add a proper support request

### ISSUE THREAD

**Issue by dgleba** [hedgedoc/hedgedoc#3496]
### Description

Having been a member of https://community.hedgedoc.org/ for weeks I am unable to post more than one image. This suppresses getting the information I believe you want to receive.

### Steps to reproduce

I spent considerable time creating the post in the picture below only to find I cannot post it.

I get the message:
![2023-03-12 18_11_15-Unable to edit existing note - Support - HedgeDoc Community](https://user-images.githubusercontent.com/4622715/224577050-d7c76d57-1ad9-4996-920e-3ffda439e91e.png)

## picture of my post - that I can't post.
https://community.hedgedoc.org/t/unable-to-edit-existing-note/980

![image](https://user-images.githubusercontent.com/4622715/224576939-9dad3b39-19d6-4f6c-ac65-d940b0099a08.png)

### Expected behaviour

I get that you require information, but you can't get the information if the controls are too tight. 

### Your Setup

n/a

### Additional context

n/a

**Comment by davidmehren** [comment]
I'm sorry you had that frustrating experience. Unfortunately, public Discourse instances require elaborate measures for spam prevention, otherwise they would get used for free hosting and spam immediately. Freshly registered users count as "new" until they interacted with the forum for a bit, and are limited during that time. After you registered your account, you should have received a bot message linking to [this blog post](https://blog.discourse.org/2018/06/understanding-discourse-trust-levels/) explaining this.
