### ISSUE TITLE
Permission update: Change realtime connections accordingly

### ISSUE THREAD

**Issue by DerMolly** [hedgedoc/hedgedoc#3701]
If a user updates the permissions of a note all existent connection need to be updated accordingly.

The permission service already sends a message to the realtime component of the backend, we just need to change all permissions of the realtime connections.

In addition the frontend need to know about this permission update and activate / deactivate certain plugins and the editor, but this should be already fixed as soon as the redux state is updated.

**Comment by Avi98** [comment]
@DerMolly  i can work on this issue

**Comment by mrdrogdrog** [comment]
Sure. But please post your implementation plan.

**Comment by Avi98** [comment]
@mrdrogdrog  here is how im planing to implement it
- subscribe to `NoteEvent.PERMISSION_CHANGE` event in realtime note service.
- check in realtime note store if the permission changed note's id is there, if yes then
- `getConnections()` of `RealtimeNote` will return all the active connections. We have current user session in `handleConnection()` of `WebsocketGateway`, if currentUser doesn't have read permission terminate  connection.
- if user has edit permission send `canEdit` to all the connections from `RealtimeUserStatusAdapter` (Not sure about this).

**Comment by mrdrogdrog** [comment]
No need to inform the clients about anything. That's already implemented. But the `RealtimeConnection` saves a boolean that indicates if the Backend is accepting updates from that connection. That needs to be updated.

**Comment by mrdrogdrog** [comment]
You get this error because the user is not allowed to read the note anymore. The change of permission triggers a reload of the note metadata in the frontend. For that the frontend is using the HTTP api via fetch. The server responses with 403 and this error isn't catched in the frontend.
You can ignore that for now because we need to think about how we want to handle such situations.

**Comment by Avi98** [comment]
Yes, But the original ask of the issue was.

> The permission service already sends a message to the realtime component of the backend, **we just need to change all permissions of the realtime connections.**

^^ this already seemed to be resolved or i'm missing anything.

**Comment by mrdrogdrog** [comment]
No, it's not resolved because the connections on the backend side need to be terminated or changed to read/write access.

Right now if a permissions is changed the backend informs the clients about the new permissions. The clients will make changes like toggling the read only state of the editor. But that's only on the frontend. 
If a user isn't allowed to read the note anymore then the backend should cut the connection. (Crash by error doesn't count).
But more important:
If a connection has been built up while the user had only read access and then the permissions are changed so the user can write, then the backend would deny his changes because the connections on the backend side is still in read only mode.

**Comment by Avi98** [comment]
Thanks @mrdrogdrog  for the helping me with the `acceptEdits` field. 

Currently im facing this issue. RealtimeNoteService is already subscribed to `NoteEvent.PERMISSION_CHANGE` event and im extracting the note permission from `realtimeNote?.getNote().groupPermissions` but im not able to get the latest permissions (goupPermission, userPermission). 

I think this is because the `RealtimeNote` is created at the time of initial connection. In order to get the latest permission on the notes in need to add the `NotesService` as dependency to `RealTimeNoteService` and the get the permission from DB by the note id to get the note's permission.

Please correct me if im wrong.

**Comment by mrdrogdrog** [comment]
Instead of reading the permissions from the database again I would rather change the event handling to send the new permissions as payload of the event emitting.
