### ISSUE TITLE
Add the feature to upload, add and link attachments/files

### ISSUE THREAD

**Issue by johannes1984** [hedgedoc/hedgedoc#3937]
### Is your feature request related to a problem? Please describe.

To make this the perfect notes app, I'd love to be able to upload file attachments

### Describe the solution you'd like

Extend the existing functionality to upload an attachment file, e.g., a PDF and then display it with a note or add it as a link.

### Describe alternatives you've considered

none

**Comment by mrdrogdrog** [comment]
Please correct the title of this issue.

**Comment by KhaaL** [comment]
Is this a feature that the Hedgedoc team find in line with the long-term vision / goals of the project? I'm very much intrested in this, but would also respect if the feature is rejected by the team (and in this case, I can look for other solutions for my needs).

**Comment by DerMolly** [comment]
We honestly don't know right now.

It won't happen soon, but it could be something we implement sometime in the future.

But we would need to discuss this again.
There are some things that need to be considered when implementing such a feature:

- you would need to be able to limit the upload size, because some people would want to upload movies and others don't want their users to be able to do this
- you also would need to have separate permissions for guests (and maybe another file size limit)
- it would be a very big problem if this general-propose file upload handles some file types wrongly (executable code e.g) or if attacks abuse this to fill your server with junk

We're aware of possible solutions to these points, however currently don't have the time to fully evaluate them as we're currently focused on finishing HedgeDoc 2.0.

In the meantime you could use external tools to upload files and link to them in HedgeDoc. So your arbitrary files are present even if the experience is less than ideal.

**Comment by 6r1d** [comment]
I'll join this request as sometimes I want to add short animations using WebM.

**Comment by appetrosyan** [comment]
> We honestly don't know right now.

This honesty is much appreciated. 

> But we would need to discuss this again.
> There are some things that need to be considered when implementing such a feature:

>    you would need to be able to limit the upload size, because some people would want to upload movies and others don't want their users to be able to do this
>    you also would need to have separate permissions for guests (and maybe another file size limit)
>    it would be a very big problem if this general-propose file upload handles some file types wrongly (executable code e.g) or if attacks abuse this to fill your server with junk

You are aware that GIFs can take orders of magnitude more space than the equivalent `mov` or `webm`?

**Comment by 6r1d** [comment]
> You would need to be able to limit the upload size
> You also would need to have separate permissions for guests (and maybe another file size limit)

While GIFs are allowed, their quality is typically lower compared to WebM.
I'll add two instances of a basic animation to demonstrate:

* [Gif](https://github.com/hedgedoc/hedgedoc/assets/2552837/e7e3d42b-a29a-4b73-900f-e23492e69238) - 2M, choppy
* [WebM](https://github.com/hedgedoc/hedgedoc/assets/2552837/fc327813-7741-4c1d-82f2-27c0b5650393) - 119.8 KiB, 60 fps

I'll be pretty happy if I can somehow switch off the upload limitations on a local server.

**Comment by ErikMichelson** [comment]
For adding webm support, please open another issue as this is separate from generic file attachments.
Btw currently this is the list of allowed mime-types: https://github.com/hedgedoc/hedgedoc/blob/develop/backend/src/media/media.service.ts#L51-L64

**Comment by ErikMichelson** [comment]
Closing in favor of #1967

**Comment by SoulFireMage** [comment]
I was surprised to find I couldn't import other markdown files I have on my system. Is this not a common use case?

**Comment by ErikMichelson** [comment]
Most people probably use the [CLI](https://github.com/hedgedoc/cli) for this. A mass-import by drag&drop is on the roadmap.
