### ISSUE TITLE
Handling profile data from external login providers

### ISSUE THREAD

**Issue by davidmehren** [hedgedoc/hedgedoc#463]
In 2.0 we want to use a 1-to-n relation between users and logins. This means that the same user can login e.g. with Google and Twitter, similar to OmniAuth used by Gitlab.

This leads us to some questions regarding updating our internal user data (currently planned to at least consist of a username, a display name, a profile picture (URL) and an email address). 'Update' in the following description means to unconditionally overwrite the internal profile.

First, lets look at a scenario where only *one* auth method is enabled. In this case we could:
1. Update the profile information on **every login**
2. Update the profile information only on signup/the **first login** and **don't** allow the user to change it
3. Update the profile information only on signup/the **first login** and **allow** the user to change it

In a scenario where multiple auth methods are enabled, it gets a bit more complicated. We could:
1. Update the profile information on **every login**, with the currently used login provider
2. Update the profile information on **every login**, using always the same ('primary') login provider. Allow the user to select the primary provider in the profile settings.
3. Update the profile information only on signup/the **first login** and **don't** allow the user to change it
4. Update the profile information only on signup/the **first login** and **allow** the user to change it

**Comment by DerMolly** [comment]
Since we want to have the config option `userCantChangeProfileData` (to make the auth provider the single source of truth) I think our solution should be like this:

### Scenario A: One Auth Provider

Update the profile information on **every login** and let the user change those information on the `/profile` page, **if** the admin **did not** set the  `userCantChangeProfileData` flag.

Obviously the information should not be overriden if the user had changed them manually before that. This bears the question if a user should be able to remove his custom information to be synced with the auth provider once more. (e.g changing all information to `""`)

### Scenario B: Multiple Auth Providers

Update the profile information on **every login**, with the currently used login provider. If the admin permits it let the user change the information.

The typical user story for this scenario, would be that the user logged in via two auth providers and then change it's personal information two something custom to avoid that they change so often.

### Additonal thoughts

What do we do if one auth provider does not provide an information we already have in the DB? e.g the user first logs in via github with a displayname and profile picture and then via ldap with only a displayname. Should the profile picture from github should be changed to default avatar or should it stay since we did not receive any other image?

**Comment by mrdrogdrog** [comment]
IMHO An update on every login is very annoying if you have multiple methods. Personally I prefer the "update on sign up".
How about an flag like "profileChangesAllowed" in the config?
If it's true then the profile information will be synced only on sign up and not on login. If it's false then the information will be synced on every login.
You could even set a 'syncProfileInformation' flag into the auth providers config. so the admin can decide if a login method should update the profile.

**Comment by mrdrogdrog** [comment]
# Example Corporate LDAP
profileChangesAllowed: false
Auth: LDAP with syncOnLogin
Result: The single source of truth is the ldap

# Example demo.hedgedoc.org:
profileChangesAllowed: true
Auth: Facebook, Google, OpenID without syncOnLogin
Result: The users profile will be created with the data from the account that created the profile. The user can change its information themself.

**Comment by mrdrogdrog** [comment]
We could even add optional options for the auth provider config, that decide which information should be synced.

**Comment by SISheogorath** [comment]
Let's try to avoid config options as much as possible. More config options only make the situation worse, rarely better.

It think it all stands and falls with password logins. If password logins are allowed, the intuition is is obviously to have local accounts. Local accounts should live on their own and only import profiles from external providers, not being managed by them.

Means:

If we have local accounts (username + password) enabled: Fill on sign-up, then the user is responsible for themselves.

If no local accounts (username + password) are enabled: Update from primary login provider (used for first sign-up).

Primary login provider is by default local accounts, if not possible because it's disabled: the login provider used. If the login provider was removed either by the user or entirely: the next login provider used to enter the account.

All educated guesses and should fit all regular use cases.

**Comment by davidmehren** [comment]
@InnayTool, @DerMolly, @ErikMichelson and I just discussed this and came up with this solution:
- A user can have multiple login providers. Zero or one of them is marked "sync source". If an external provider was used to create the account, it is automatically used as sync source.
- The admin can use a config option do disallow changing the sync source.
- If not disallowed, the user can change the sync source in their profile page. If the sync source is set to "none", username, display name, email and profile picture are editable.
- On login, the profile data gets updated from the used login provider, if it is set as sync source.

**Comment by davidmehren** [comment]
I wrote down a slightly modified version of the above proposal in #1032.  
Please have a look over there and check if it meets all use-cases.
