### ISSUE TITLE
Mermaid diagrams styling: edge labels have wrong margins

### ISSUE THREAD

**Issue by benjaoming** [hedgedoc/hedgedoc#4894]
### Description

Thanks for a great project :heart:

I'd love to use the Mermaid diagram feature more, but currently there's an issue with how labels are placed. Maybe it's something related to CSS rules?

![image](https://github.com/hedgedoc/hedgedoc/assets/374612/6288263f-2b38-4f8a-9a84-f00288df1da9)

### Steps to reproduce

Example code:

``````
```mermaid
sequenceDiagram

actor Individual
Individual->>+Application: Perform an action


```
``````

### Expected behaviour

Example rendering on GitBook

![image](https://github.com/hedgedoc/hedgedoc/assets/374612/a86c4fe6-83d2-4f04-9b80-07c29da2dc33)

### Your Setup

https://demo.hedgedoc.org

**Comment by mrdrogdrog** [comment]
Hello,

I don't see any interference from the CSS. Seems like Mermaid just calculates the positions incorrectly.
Also interesting: The problem doesn't occur in Chrome. Only Firefox. (haven't tested any other browser)
![image](https://github.com/hedgedoc/hedgedoc/assets/6124140/9cd4f7fe-9d96-4a93-857e-f1845da37d56)

This could be caused by the used mermaid version because it also doesn't occur in firefox with HedgeDoc 2, which uses the latest mermaid version 10. HedgeDoc 1 uses mermaid 9.
![image](https://github.com/hedgedoc/hedgedoc/assets/6124140/fc019d3c-e855-44c6-a359-d6ae3ca5aa1b)

We don't fix non-critical bugs in HedgeDoc 1 anymore because every change in HD1 can lead to unpredictable side effects and we rather focus on HedgeDoc 2.
This is explained in the [Readme file](https://github.com/hedgedoc/hedgedoc#state-of-the-project)

**Comment by benjaoming** [comment]
Thanks for explaining @mrdrogdrog :pray: 

I see the point, and yeah it's very interesting that the positioning is different in Chrome... will see if I can report it for Mermaid or find a related issue :+1:

**Comment by benjaoming** [comment]
I can reproduce the issue on https://mermaid.live - which could indicate that this is not an issue with the latest Mermaid?

Hunting for issues in Mermaid itself, I found that [10.2.0](https://github.com/mermaid-js/mermaid/releases/tag/v10.2.0) released in May with the note:

> Fix regression errors in sequenceDiagrams by @knsv
