### ISSUE TITLE
Authorship highlighting for anonymous edits

### ISSUE THREAD

**Issue by nidico** [hedgedoc/hedgedoc#505]
In CodiMD, edits from anonymous users are currently not highlighted with authorship colors.

According to https://github.com/hackmdio/codimd/issues/588#issuecomment-336625830, this is because authorship information isn't currently stored for guest edits.

As "authorship colors" is a very popular feature (e.g. amongst current Etherpad users), this is a severe limitation in functionality for guest users. However, guest usage (by sharing a cryptic URL in a trusted channel) is an important (and very accessible!) way of usage, so we might want to address this.

Are there strong arguments against it?

- Privacy? I don't think so - some random token stored in a cookie should be sufficient, no personal data should be involved.
- Database bloat? I doubt.
- Others?

What would need to be done?

**Comment by SISheogorath** [comment]
One oft the major questions that come to my mind with such a feature: What details about authorship do we want to store?

Even you do don't consider a cookie in a browser cache a problem, the privacy laws in Europe actually do. The answer to why they are used and don't need to be explicitly spelled out is that they are usually setting or authorisation cookies. Both are technically required to establish a user sessions, which for a user, can be considered part of the contract that they engage in, when they sign up/in. However, doing this for anonymous users, in a away that allows to re-identify them after they left the page or alike, this can not be considered part of the contract but mandates as pseudonymous tracking and is therefore subject of Article 6 section 1 lit. f, requiring user consent.

Besides that, even when we only record authorship while users are on the same pad and while the tab itself is open, we can ask the question, what's the value of a random generated number associated with the authorship. To be really useful it would require a name attached to it. We can generate them, then we might get around the PII topic, but most likely we want something more useful in there, maybe allowing people to declare their own name. This is 100% PII but intentionally given, so one can argue with Article 6 Section 1 lit. a or b.

But back to the mentioned main question:

So what is expected to be visible? A name, the changed parts, (due to revisions) the time of changes, a possible identifier for a cookie(?), anything else?

**Comment by davidmehren** [comment]
I see it as the responsibility of the party hosting a HedgeDoc instance to ensure it complies with the relevant laws, so I wouldn't dismiss a feature if it *might* require consent on a public instance hosted in the EU.

> what's the value of a random generated number associated with the authorship

Etherpad actually does not show an identifier for the author, until one is manually entered. It just shows the same color for all edits the author makes. So just preserving the same color through all revisions of a note is what I would call "minimal featureset" here.

We could additionally randomly generate names for anonymous authors (e.g. something like "ecstatic octopus"), which makes it easier to refer to other authors than using colors like"light purple".

**Comment by InnayTool** [comment]
A way to implement this feature in the database is to bind a authorship color (from our 2.0 plantuml) file to a session and not to a user. This requires a cookie for every user who edits the document.

**Comment by InnayTool** [comment]
In #1266 adds an author which is connected to a session and the user. This author has an color which is the authorship color. For an author it is not required to have an user set, so colors for anonymous edits should be possible to implement with this.

**Comment by davidmehren** [comment]
This is now tracked for implementation in https://github.com/hedgedoc/hedgedoc/issues/5016
