### ISSUE TITLE
Prevent Problem with colons for e.g. list introductions

### ISSUE THREAD

**Issue by DerMolly** [hedgedoc/hedgedoc#5251]
### Description

If you type `:` in the HedgeDoc 2 Alpha it autocompletes to `:+1:`. This is very irritating when trying to start a list like this.

```
Reason we should do this:
- Reason 1
- Reason 2 
```

### Steps to reproduce

Try to write

```
Reason we should do this:
- Reason 1
- Reason 2 
```

in https://hedgedoc.dev

### Expected behaviour

Either we should prevent the autocompletion if the `:` is at the end of a word (This is how it's done in GitHub it seems).

OR

We add a default suggestion to the list of emoji autocompletion like we did for the code blocks.

### Your Setup

-

**Comment by Raphael124** [comment]
Suggestion :
Only give emoji quick access when at least one letter is typed (ex: `:+` should suggest `:+1:` but `:` should not be treated as a potential emoji picker selection trigger, likewise `:c` would suggest `:church:` or `:cactus:` but only once the c is typed).

The fact of preventing the autocompletion if the `:` is at the end of a word is not sufficient IMO because in some languages there is a space between words and colons (such as French).
