### ISSUE TITLE
Can't register a new user on https://pad.cas.cat/

### ISSUE THREAD

**Issue by ipoddine** [hedgedoc/hedgedoc#5253]
### Description

I'm trying to register on https://pad.cas.cat/ but when the sign in popup appears, it doesn't let me click on the register button it does nothing.

### Steps to reproduce

1. Go to: https://pad.cas.cat/
2. click on any "sign in" button in the page
3. a popup opens on top of the page with an email field, a password field, a blue button to Sign In and a white button to Register
4. fill in the email field with a valid email address
5. fill in the password field with a password with 25 chars, containing upper and lowercase chars, numbers and special chars and no dictionary words
6. the Register button is still white 
7. when clicking on the Register button, nothing happens
8. when clicking on the Sign In button, nothing happens either

### Expected behaviour

The Register button activates (maybe changing to blue?)
when I click on the Register button something happens (many things can happen, but nothing in this case is not really an option)
I would expect to get a confirmation of the registration or an error if something is wrong. Maybe also to receive an email.

### Your Setup

- Host OS: [e.g. Ubuntu 20.04]
- NodeJS version: [run `node --version`]
- HedgeDoc version: (Click "Releases" in the footer)

### Additional context

I already tried to refresh the page and to exclude the ad blocker on this page

**Comment by DerMolly** [comment]
Hey @ipoddine,

first of all I'm assuming you write this issue, because your the admin of https://pad.cas.cat/  and you are confused why registering does not work, correct?

You're right there should be some kind of response and I can confirm that there is a problem with this instance. The register button does change (but it's not super noticable) and it does so on this instance, so I'm not super sure what the problem is.

First of all it'd suggest you update to the latest release (the version hosted is quite old) and test again.

If this issue persists, we would need a bit more info about your config (please remove any sensitive information e.g passwords) to debug further.

**Comment by ipoddine** [comment]
Hi @DerMolly ,
actually nope, I'm not an admin of https://pad.cas.cat/ and I'm quite new to this, so I guess I would need to contact the administrator of pad.cas.cat first. I will update if anything else is needed, thanks!

**Comment by ErikMichelson** [comment]
When accessing the page, I see many errors like this:
```
Mixed Content: The page at 'https://pad.cas.cat/s/release-notes' was loaded over HTTPS, but requested an insecure stylesheet 'http://pad.cas.cat/build/emojify.js/dist/css/basic/emojify.min.css'. This request has been blocked; the content must be served over HTTPS.
7
```

This indicates that probably the instance administrator has either not configured `CMD_PROTOCOL_USESSL` correctly or their reverse-proxy is not set up properly.
