### ISSUE TITLE
Proposal: Replace OT with CRDTs

### ISSUE THREAD

**Issue by MazeChaZer** [hedgedoc/hedgedoc#527]
I've been reading about Conflict-Free Replicated Data Types (CRDTs) lately and it looks like they would be a good fit for HedgeDoc if the current Operational Transformation (OT) implementation should be replaced.

CRDTs are more powerful than OT because they don't need a central server for coordination. This could allow for P2P-scenarios and relieve server load when many persons edit the same document concurrently.

[Here](https://josephg.com/blog/crdts-are-the-future/) a previous Google Wave developer describes why CRDTs are (in his view) the way to forward in contrast to OT. The linked talk given by Martin Kleppmann gives a good overview of the current state of art and remaining challenges. The JavaScript library Yjs looks very promising and is reviewed in detail in [this blog post](https://blog.kevinjahns.de/are-crdts-suitable-for-shared-editing/).

Of course this is by no means urgent and I probably won't have the time to do this myself soon, just wanted to document the idea for now.

**Comment by ccoenen** [comment]
I've now read up on CRDTs, and they do look very interesting. I'm a little bit worried about feature creep for 2.0. But I'm not actively developing any of the parts, so that's not up to me to decide anyway.

From what I've read, Yjs is practically developed especially for our use case. And looks well-supported and stable, including a [binding for codemirror](https://docs.yjs.dev/ecosystem/editor-bindings/codemirror).

One thing I would like to make sure, though, is to keep the high rate of live updates that we know from our current OT-implementation. You can see people typing as they do it, and it's a very direct and low-latency communication. Yjs seems to be able to combine edits into larger chunks, which (if I understand it correctly) is where much of their optimisations come from. If this is at the expense of a 100ms refresh time (rough estimate) then I would prefer smaller chunks over smaller history. This is a thing that should be tested before committing to either protocol.

Another thing that I can't confirm right now, is how cross-platform compatible Yjs or other libraries are. With OT, there are implementations in pretty much any language, and if not, they are trivially implemented. It is not something we immediately need, but I wouldn't dismiss this either.

**Comment by davidmehren** [comment]
@ErikMichelson and @DerMolly had a look at Yjs and were able to quickly build a prototype. Therefore, we plan to use Yjs to build the real-time component of HedgeDoc 2.0.

**Comment by ErikMichelson** [comment]
@DerMolly and myself wrote some points together:


# Realtime communication

## y.js

We evaluated y.js's CRDTs for use in HedgeDoc 2 and put something that works remarkably fast together. The main benefits in our evaluation are that they can handle disconnects (it's even feasable to allow offline editing and later resyncronisation) and the ease of use of the library. Y.js is also known as one of the [best CRDT implementations](https://josephg.com/blog/crdts-go-brrr/) for JS/TS.

## websocket vs socket.io

In the past it was very hard to keep up with socket.io updates, because of the way our code was interlocked with it. As websockets are easily available on both ends and our limited testing has shown that using websockets in nestjs is reasonably easy and makes it possible to handle channels (notes) and implement custom HedgeDoc messages (user goes online/offline, permission changes, instance update, etc.) over the same sockets, we'd recommend going with the default websocket instead of the extra layer of socket.io. Especially if one considers that the main advantage of socket.io is the ability to fallback to long-polling, something that's not needed with y.js or CRDTs in general. 

## Auth
With a websocket connection there are four possibilities to send some kind of authorization information:
1. Using a cookie which is sent with the HTTP Upgrade request.
2. Using an `Authorization` header in the HTTP Upgrade request.
3. Sending the information as a "handshake" message via the websocket.
4. Appending the information to the request URL.

HedgeDoc 1 uses socket.io which does the fourth method. The note id as well as the session id are  appended as a query parameter to the socket.io URL.

y.js has built-in support for adding custom query parameters, so we could easily use that for transferring the auth information.

The connection however is initiated by the `y-websocket` module which has no options for configuring either custom headers or handshake messages. So if we wanted to use option 1, 2 or 3, we'd have to build our own websocket module for y.js.

**Comment by ccoenen** [comment]
> we'd have to build our own websocket module for y.js.

I'd first try to request this ability upstream. I don't think this is an unreasonable functionality.

**Comment by InnayTool** [comment]
By using y.js we are using CRDTs now.
