### ISSUE TITLE
Add imgur MediaBackend

### ISSUE THREAD

**Issue by davidmehren** [hedgedoc/hedgedoc#538]

**Comment by InnayTool** [comment]
Maybe relevant for this topic: #927

**Comment by DerMolly** [comment]
So I just did some research:

There are some npm packages that we could use:
- [imgur](https://www.npmjs.com/package/imgur)
  This seems to be the big player with 8,318 weekly downloads.
  But the last update is sometime ago (September 2018)
  According to the [README](https://github.com/kaimallea/node-imgur/blob/master/README.md) they are working on TS Rewrite, but this seems to abandoned
  [And it uses requests (which is deprecated)](https://github.com/kaimallea/node-imgur/issues/99)
  [Also there are five open PRs (besides dependabot PRs)](https://github.com/kaimallea/node-imgur/pulls?q=is%3Apr+is%3Aopen+-author%3Aapp%2Fdependabot)
- [imgur-uploader](https://www.npmjs.com/package/imgur-uploader)
  113 weekly downloads
  Last Update: June 2017
  seems rather barebones
- [imgur-file-uploader](https://www.npmjs.com/package/imgur-file-upload)
  14 weekly downloads
  Last Update: November 2019
  The [only issue](https://github.com/alirealasad/imgur-file-upload/issues/1) is open since October 2020 and didn't get any answers (tbh is the issue a bit barebone so maybe that's the reason)
- [imgur-upload](https://www.npmjs.com/package/imgur-upload)
  33 weekly downloads
  Last Update: May 2013
  This seems to be the 'classic' package

**Comment by davidmehren** [comment]
Well.
I see two options:
- Drop imgur support
- Build the upload ourselves (Seems to be just a POST to https://api.imgur.com/3/upload according to [the docs](https://apidocs.imgur.com/#c85c9dfc-7487-4de2-9ecd-66f727cf3139))

**Comment by SISheogorath** [comment]
I could imagine to drop imgur support. It won't hurt much, as the uploaded images stay available.

**Comment by DerMolly** [comment]
It was our default in 1.x, don't know if it's such a good idea to drop the support with 2.0. I mean it's the best point to do so, but on the other hand I'm hesitant as there should be quite a few instances that use this…
