### ISSUE TITLE
List of notes owned by a particular user (including "My notes")

### ISSUE THREAD

**Issue by rastapopougros** [hedgedoc/hedgedoc#54]
https://github.com/hackmdio/codimd/issues/653

A page for each user, with the list of all owned notes.

Also, for ourselves, we must have the link for "My notes" in the tabs menu with "History" and "All notes" (#53).

If one day there is a group functionnality, in "My notes", we must see also notes owned by our groups. The purpose is to see "all notes where I'm admin, where I can change the config".

**Comment by ccoenen** [comment]
They are already in a work-in-progress pull request for a personal profile page:

https://github.com/codimd/server/pull/34/files#diff-c20808cd50fa2d6520d58aa115e52a07R23

(should be noted that I'm not arguing that this is the perfect place to put it, I'm merely stating that I find your suggestion very useful!)

**Comment by davidak** [comment]
It's strange that this feature not exists because it's a pretty critical usability issue. I would consider it basic functionality while "last opened files" is a nice to have.

You can get into the situation where you own a note, but have no access to it!

That happens when you import it with the cli and open the web ui then (without opening the notes URL directly).

This means, when you clear the history, you loose access to all your notes unless you remember their ID. This should have a high priority.

**Comment by ccoenen** [comment]
Yes, it is strange.

It _is_ part of the Profile pull request I started quite a while back. This is one of the things that will be part of a 2.0 release.

**Comment by InnayTool** [comment]
The new public API implements it with route: `/api/v2/me/notes`.

**Comment by davidmehren** [comment]
To centralize the discussion about this topic, I created https://github.com/hedgedoc/hedgedoc/issues/994.  
Please take a look and comment if you feel I missed an important aspect.  
Thanks!
