### ISSUE TITLE
SAML Endpoint returns 404 Not Found

### ISSUE THREAD

**Issue by Daniel-CS-Team** [hedgedoc/hedgedoc#5606]
### Description

As per[ HedgeDoc's documentation](https://docs.hedgedoc.org/guides/auth/saml/) I should be able to download metadata XML from `{{your-serverurl}}/auth/saml/metadata`, but this returns a 404.
I went ahead anyways to configure SAML, but it still does not work, as `{{your-serverurl}}/auth/saml/callback` returns a 404 as well. This renders SAML authentication totally broken. 

### Steps to reproduce

1. try to access `{{your-serverurl}}/auth/saml/metadata`
2. Observe 404

### Expected behaviour

SAML should work as described in the documentation

### Logs

```shell
2024-08-27T06:08:03.986Z info: 10.104.24.195 - - [27/Aug/2024:06:08:03 +0000] "GET /auth/saml/callback?SAMLResponse=***REDACTED*** HTTP/1.1" 404 - "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:129.0) Gecko/20100101 Firefox/129.0"
```

### Config

```shell
CMD_SAML_IDPSSOURL=https://{{authentik-server}}/application/saml/hedgedoc-saml/sso/binding/redirect/
CMD_SAML_IDPCERT=/hedgedoc/SAML-Signing_certificate.pem
CMD_SAML_DISABLEREQUESTEDAUTHNCONTEXT=true
CMD_SAML_ISSUER={{your-serverurl}}
```

### Your Setup

- AWS FARGATE
- NodeJS version: as per latest Docker-Image
- HedgeDoc version: 1.9.9

**Comment by ErikMichelson** [comment]
I'm sorry, but I can't reproduce your problem while trying with Authentik using the same environment variables as yours.
The metadata endpoint exists and returns no 404. The callback endpoint however does return 404 on GET requests as it only allows POST-binding.

Configure your authentik provider like this and don't forget to select your signing certificate under advanced settings.
![image](https://github.com/user-attachments/assets/16e9dfca-5a03-4ba5-966f-497a75409a01)

In general if you're planning to continue using authentik, I'd personally rather use the OAuth2 integration since you don't have to handle with expiring certs there.

**Comment by Daniel-CS-Team** [comment]
Thanks, using Post fixes the issue indeed.
Would be nice to highlight this in the documentation.
