### ISSUE TITLE
Pandoc export

### ISSUE THREAD

**Issue by joachimmathes** [hedgedoc/hedgedoc#618]
What are your plans regarding the port of the CodiMD Pandoc export feature to HedgeDoc?

**Comment by DerMolly** [comment]
It sounds like a possible solution to support a wide variety of exportable formats, but we don‘t intend to release any 1.x releases anymore. We would need to build something different for 2.0, because 2.0 is a complete rewrite with another code base.
So we‘ll come up with something, but we can‘t just copy the code over.

**Comment by b3** [comment]
Maybe you can directly reused pandoc code as it was done by https://github.com/osener/markup.rocks.

That would directly offer a lot of very nice feature already largely tested and a wide variety of export features.

**Comment by davidmehren** [comment]
Hi all!
I just opened #965 as a place to discuss different options for reimplementing PDF-export.
If you have any ideas or comments which are not yet in my list, please comment there!
