### ISSUE TITLE
Offline/local files support?

### ISSUE THREAD

**Issue by utybo** [hedgedoc/hedgedoc#658]
**Is your feature request related to a problem? Please describe.**

Hedgedoc is a phenomenal tool. I've converted a few friends to it, and they really like it to. But I am kinda bummed by the fact that it's not a really usable tool without an internet connection. I also don't like the fact that it relies on "external" instances: i'd really like to be able to store files on my computer, not in the cloud.

**Describe the solution you'd like**

A standalone desktop version could work. This could be just a PWA (so we can "install" a hedgedoc instance on our computer directly) or something more elaborate. It would also support offline use and creating documents locally instead of in the cloud (even if that means no collaboration on them).

**Describe alternatives you've considered**

Offline support without a PWA is probably possible, otherwise i'm not sure what other alternatives are possible

**Additional context**

Not sure what to put here, so I'll just say massive thanks for maintaing Hedgedoc <3

**Comment by DerMolly** [comment]
We're thinking about offline support, but more in the vain of you editing your notes while you don't have any internet connection and syncing up afterwards, when you have an internet connection again.

Also I'm a bit unsure what you exactly mean with "external" instances. A user is from on instance of hedgedoc and while you of course need to trust the maintainer of that instance, if that's not yourself, we don't really have any "external" instances…

Regarding a desktop app:
I think this is a bit out of scope, since this project is a collaborative markdown editor first and foremost.

If you really want to use HedgeDoc only on your own machine, you could just host an instance locally and use it like that. Maybe that is an idea worth perusing for your use case?

**Comment by utybo** [comment]
Yeah, I guess that could work. My feature request probably doesn't make sense if collaboration is the absolute prority, so I'll close it.

My main point was that I didn't really want to depend on Hedgedoc instances on the web to use Hedgedoc, so eh. I guess other Markdown editors would be more appropriate for this, but man do I love the Markdown dialect Hedgedoc uses.

Is there an issue I can keep an eye on for the oh-no-my-internet-broke offline support?
