### ISSUE TITLE
Image upload error: Provided file extension does not match MIME-type

### ISSUE THREAD

**Issue by allgoewer** [hedgedoc/hedgedoc#744]
**Description**
I updated from codimd to hedgedoc today. I'm using minio as a backend for picture upload. Trying to upload images results in the following error. **The same config works with my old codimd setup**

```
error:         Image upload error: Provided file extension does not match MIME-type
```

**To Reproduce**
1. Install latest hedgedoc
2. Setup minio as pic-upload backend
3. Upload image (a regular old jpeg) to note

**Expected behavior**
I expect the upload to succeed.

**Config**

I'm using the following config snippet
```
"minio": {
    "accessKey": "codimd",
    "secretKey": "********",
    "endPoint": "*********",
    "secure": true,
    "port": 443
},
"s3bucket": "codimd",
"imageUploadType": "minio"
```

**Your Setup (please complete the following information):**
 - Host OS: CentOS 7
 - NodeJS version: v10.23.0
 - HedgeDoc version: 1.7.2

**Comment by DerMolly** [comment]
Hey @allgoewer,

it seems the lib we use to identify the file type and check that it's extension is valid, says JPEG-images should have the extension `.jpg` and not `.jpeg`. [see here](https://github.com/sindresorhus/file-type/blob/master/core.js#L140)

We started doing this because of a security issue as described [here](https://github.com/hedgedoc/hedgedoc/security/advisories/GHSA-wcr3-xhv7-8gxc).

For the time being I'd suggest you rename your files before uploading.

We'll investigate how to mitigate this problem in a future release.

**Comment by davidmehren** [comment]
Fixing this is a bit annoying:
We either need to provide a custom extension that maps additional extensions (here `.jpeg`) to the "canonical" (at least as file-type is concerned) extension (here `.jpg`). We will probably never manage to collect all the aliases, so this might still cause failures.
We could also, instead of checking that the type from the magic matches the extension from the user, just always rename the file using the "canonical" extension from file-type, but this would require us to rework the upload logic.

**Comment by yeoldegrove** [comment]
I am also experiencing this with `.png` and `.svg` files.
* HedgeDoc version: 1.7.2

**Comment by DerMolly** [comment]
Would you be able to provide said `.png` and `.svg` files? You could also send them to me via Matrix if you like (@dermolly:kif.rocks)

**Comment by yeoldegrove** [comment]
Here is a [link](https://documentation.suse.com/sbp/all/html/SLES4SAP-hana-sr-guide-PerfOpt-12/images/SAPHanaSR-ScaleUP-MultiTarget.svg) to the `.svg` file i downloaded and tried to upload to hedgedoc.
I exported it  to `.png` via `inkscape`.

**Comment by yeoldegrove** [comment]
By the way... it is working fine when I add the same image via `![](https://link.to.image.svg)`.

**Comment by DerMolly** [comment]
The `.svg` is found to be
```
typeFromMagic = Object {
	ext: "xml",
	mime: "application/xml"
}
```

**Comment by yeoldegrove** [comment]
> A `.png` I exported via inkscape from the same `.svg` did upload just fine…

You are right. Just double checked and it works for me too.

**Comment by ErikMichelson** [comment]
Seems our file-type library doesn't support svg detection (https://github.com/sindresorhus/file-type/issues/32). Maybe we could use [`is-svg`](https://www.npmjs.com/package/is-svg) for checking files detected as xml.
