### ISSUE TITLE
merge cells in tables

### ISSUE THREAD

**Issue by mzechmeister** [hedgedoc/hedgedoc#849]
Is possible to merge cells in tables?
I can't find it in the documentation.
Thus such a feature would be a nice to have.

**Comment by SISheogorath** [comment]
First of all, it would be great if those questions would move to the [forum](https://community.hedgedoc.org). There they are way easier to find by a search engine.

But anyway, since we are already here, let's solve your issue :)

Currently it's not possible to merge cells and as far as I can tell, neither [CommonMark](https://spec.commonmark.org/), which we derivate from, nor the [GitHub Flavoured Markdown](https://github.github.com/gfm/), which our table feature took inspiration from, is able to do that.

**Comment by DerMolly** [comment]
There is already an request for this feature [here](https://github.com/hedgedoc/react-client/issues/724). And as you can read over there, too, since markdown accepts normal HTML, you can always use that for the time being:

```
<table>
  <tr>
    <td>One</td>
    <td>Two</td>
  </tr>
  <tr>
    <td colspan="2">Three</td>
  </tr>
</table>
```

**Comment by mzechmeister** [comment]
Ok, thanks for the response.

PS: [forum](https://community.hedgedoc.org/) needs another login...

**Comment by DerMolly** [comment]
> PS: [forum](https://community.hedgedoc.org/) needs another login...

You can use your GitHub Account. I do so myself.
