### ISSUE TITLE
Should we encode the note UUID in base64Url?

### ISSUE THREAD

**Issue by DerMolly** [hedgedoc/hedgedoc#864]
I'm currently working on the Notes Service and thinking about this ToDo:

https://github.com/hedgedoc/hedgedoc/blob/515e1ad9f208bcf1790a024e103c245901db33a7/src/notes/notes.service.ts#L200-L201

I guess - if at all - we would want the UUID to be converted to base64Url as the id of a note is frequently used in urls.

But my question is: Is that a good idea anyway? Because we save the UUID in the DB, we would need to decode the base64Url everytime we get a id from the user to work with it and I can't see the advantage of doing so.

**Comment by SISheogorath** [comment]
PostgreSQL has an own UUID type, which we use if we recall correct.

https://www.postgresql.org/docs/13/datatype-uuid.html

This could have an impact on the index speed.

**Comment by DerMolly** [comment]
I think I made myself unclear here:
The mentioned ToDo and Code Snippet is from `toNoteMetadataDto` that is part of `toNoteDto`. This is just a transformation that happens, when a user receives a note object from the API. In the DB we would in any case use a UUID (or at least I currently don't want to touch that).

**Comment by SISheogorath** [comment]
In this case I would also suggest to use the base64url version of have an additional field for it to release the clients from the need to have a broken implementation for it :)

**Comment by InnayTool** [comment]
For reference #522.

**Comment by InnayTool** [comment]
My proposal is to have a normal database `id` in the database, a `name` of the note which is used in the URL to access the note.
For notes which were created with an predefined URL, I would store this in the name field, because we don't need another identifier for that. If no predefined URL is given, we could generate a 256bit cryptographic secure random string which should be base64url encoded, so that nobody can guess the URL.
The normal database `id` would be better for performance and joining than an random string.
For migrating old I think it's best to take the old id or alias (if it is set) and put it in the name field.
This is only a problem if anybody uses the generated id of the note in 1.X even if an alias is set. I don't know a way to get this Id without looking in the database directly, but maybe there is one I didn't recognize. ^^
If there is one, there would be the possibility to add an `alias`. This would provide the possibility to add an alias after note creation.

**Comment by ErikMichelson** [comment]
How do you "calculate" the short URL (used by /s/... or /p/...) from the random name?

**Comment by davidmehren** [comment]
To expand on this:

In 2.0, every note has an `id`, the database primary key. Currently, this is a `UUIDv4`. Unfortunately, as it turns out, databases don't guarantee to generate this UUID in a cryptographically random way. This means we can't directly use the `id` as the *public identifier* (e.g. in the URL), as it may be guessable.  
Therefore, we need another, secure identifier we can use publicly. I wouldn't call it `name`, as that is very ambiguous. `publicId`, `urlId` or similar makes the purpose much clearer.

In addition, a user might create a note with a custom alias or add an alias at a later time (if we decide to implement the latter). This alias is then used as the canonical way to address a note. If we *don't* allow to add an alias after the note was created, it would be possible to store the public identifier and the alias in the same database field, as they are mutually exclusive.  
Still, I would prefer using separate fields, as that makes adding the "add an alias after creation" feature much easier.

When looking at the situation in 1.x, it gets a bit more complicated:
- There is a random-looking note ID that can either be an LZstring or base64url encoded version of the database UUID.
- There is a short version of the note id that is used for the publish and presentation views.
- A note can also be addressed using an alias.

Only the alias from 1.x maps cleanly to the current database design in 2.0.  
2.0s public identifier will need to be newly generated to ensure consistent security.  

Notes should also remain accessible under their legacy long & short IDs. This can be achieved in two ways:
- Adding more database fields like `legacyId` and `legacyShortId` and store the old IDs in there.
- Rearchitect the database so that it is possible for a note to have multiple aliases. The old IDs could then be added as aliases and the note would remain accessible.

It might make sense to choose the second route, as having multiple note aliases sounds like a nice to have feature.

**Comment by DerMolly** [comment]
I too think multiple aliases is the way to go. Can we still use the findOne function of TypeORM for this search pattern? A quick google search suggests to that it should be possible, but maybe be a bit less pretty than the current way. See https://stackoverflow.com/questions/58475174/how-do-i-query-an-array-in-typeorm

**Comment by davidmehren** [comment]
This solution seems to be postgres-specific. I would simply not use an inline array (ugly!), but instead a separate table that maps aliases to note IDs.

**Comment by DerMolly** [comment]
Can we easily query with that? Or would we need to complicate the `getNote` method a bit?

**Comment by DerMolly** [comment]
I just thought maybe having the legacyId etc. fields would be a better idea.
We could replace the content of the url bar from the old url to the new url in the 2.0 frontend or give HTTP Error 302 or better 307 as a response if the old note is requested (That should bring at least some programs to save the new url instead of the old). Then we could eliminate these old urls in a later update (3.0) and get rid of them entirely instead of carrying them around for all eternity.
On the other hand any good admin will tell you a URL should never break, so that's maybe not the best idea…

**Comment by ErikMichelson** [comment]
Well, I really like the idea of having multiple aliases for a note. In that case I'd also prefer the additional alias-note map. With TypeORM I'd guess that it wouldn't change much of the implementation.

We just have to think about the history entries. How do we ensure to not get two entries for the same note with different aliases?

**Comment by DerMolly** [comment]
> We just have to think about the history entries. How do we ensure to not get two entries for the same note with different aliases?

At least for the backend that is relatively easy as the HistoryEntry is directly linked to the note via the internal id (which is the same regardless of the alias used).

Not to sure how the guest-only history (in LocalStorage) works there. Maybe that could be tricky…

**Comment by InnayTool** [comment]
I think it's reasonable to have a table for aliases and drop all other fields for the url in the note table.

And I don't think the guest-only history should be a blocker for anything in the backend.

**Comment by InnayTool** [comment]
This should also mitigate the problem described in #101.

**Comment by davidmehren** [comment]
To summarize, in 2.0, a note will have:
- a primary key (currently a UUID, but can probably be just an integer?)
- a `publicId`, which is a random and URL-safe identifier to be used in the URL
- zero or more `aliases`, which will be used to store the legacy IDs and (new) aliases

If everyone is happy with that, I think we can wrap up here and open implementation issues.

**Comment by InnayTool** [comment]
Why do you want an explicit `publicId`? I think it would be enough to specify that a note must have one or more `aliases` and all types of identifier are stored in an alias row.

**Comment by ErikMichelson** [comment]
On the other hand: Should aliases redirect to the public id? If that's the case, I'd support @davidmehren's way. Otherwise I'm preferring @InnayTool's idea.

**Comment by SISheogorath** [comment]
They should not redirect. It'll make "shared URLs", which AFAIK are planned for 2.x way more complicated. First of all, you'll need to track a sessions from the shared URL from that moment you redirect, and you'll also make it harder for a user to use the frontend. Just taking the URL someone is using and sharing it with someone else, will result in working for user A, because they previously used the shared link with permissions attached, but not for user B, who got a copy from the URL of user A.

Alternatively we could add a parameter to track that, but honestly, it just makes things unnecessarily complicated.

**Comment by davidmehren** [comment]
The key point is if we want to have a "canonical external identifier". Internally, we of course have the primary key, but we don't want to leak that.
If we don't have a separate `publicId` column, a note must be identified by one of its aliases. This creates some problems:
- What happens when you want to remove the last alias of a note?
- How do we make sure a user cannot remove the random id which we would now just add as an alias?

Another thing: In the internal API, do we want to continue using the alias for realtime-communication or does it make sense to use a canonical ID?

**Comment by ErikMichelson** [comment]
Actually your last question is the question I asked myself and was the reason I suggested having one canonical (random) id with all aliases redirecting to the canonical URL.

Another thing is that we have to consider whether the aliases are identical to the "shared URLs" that include certain permissions, mentioned by @SISheogorath. Until now I thought that these are different things, but maybe it really seems useful to combine this.

> How do we make sure a user cannot remove the random id which we would now just add as an alias?

What would be the problem of that?

> What happens when you want to remove the last alias of a note?

This just must not happen. There needs to be some kind of controller that counts the aliases prior removal.

**Comment by InnayTool** [comment]
Another question appeared from #101 should we allow case sensitive noteIds? This has the disadvantage that some browsers autocomplete in a wrong way for that and open the wrong note.

**Comment by SISheogorath** [comment]
Given that the RFCs for URLs are quite clear on that, and it helps with encoding, we should keep case-sensitive noteIds. For aliases, we might want to handle them all lower-case for the sake of simplicity as people might type them manually into a URL bar and it can easily become frustrating. What we should definitely not do is storing them in a case-senstive form and then allow case insentive requests. That just makes database queries and regexes and everything else slow. Store them in lowercase and and convert all requested aliases to lowercase.

**Comment by DerMolly** [comment]
@InnayTool, @ErikMichelson and myself tried to come up with a proposal for the notes. The result can be seen here #1045.
