### ISSUE TITLE
Warn user when DB is configured to be sqlite?

### ISSUE THREAD

**Issue by DerMolly** [hedgedoc/hedgedoc#880]
I was just thinking, that we intend sqlite only for development as it is easier to spin up than a postgres or mysql/mariadb and to that end provide a .env.example file that is using sqlite. New users could just start the app with the .env.example file and would then use sqlite.

Should we display a warning when HedgeDoc starts with a sqlite DB configured?

**Comment by davidmehren** [comment]
Warnings tend to get ignored. See all the users who are confused about broken things because they don't set `CMD_DOMAIN` and didn't read the warning. An idea could be to not start with a sqlite db without an explicit (and non default) config flag.

That said, I would not degrade sqlite to a develop-only setup. Using sqlite is probably reasonable for many smaller setups, provided care (like backups) is taken.

**Comment by DerMolly** [comment]
I thought about that too. I was also torn about what such a warning should tell the user, if we agree that some people want to use sqlite in production. Maybe we shouldn't warn and just make sure that our installation guide makes it clear, that using one of the other DBs is probably better? (I kind of hate the tone of that tbh, but am currently unable to come up with a better sentence)

**Comment by davidmehren** [comment]
We decided with #932 to support SQLite, so I think we can close this.
