### ISSUE TITLE
CSP Rules

### ISSUE THREAD

**Issue by dbrgn** [hedgedoc/hedgedoc#923]
When enabling the content security policy, the following header is sent:

> Content-Security-Policy: default-src 'self'; script-src 'self' vimeo.com https://gist.github.com www.slideshare.net https://query.yahooapis.com 'unsafe-eval' https://disqus.com https://*.disqus.com https://*.disquscdn.com https://www.google-analytics.com 'nonce-a16bbb39-97c0-47b3-97f2-08c640f3e35c' 'sha256-81acLZNZISnyGYZrSuoYhpzwDTTxi7vC1YM4uNxqWaM='; img-src *; style-src 'self' 'unsafe-inline' https://github.githubassets.com https://*.disquscdn.com; font-src 'self' data: https://public.slidesharecdn.com https://*.disquscdn.com; object-src *; media-src *; child-src *; connect-src *

Any idea why things like yahooapis.com (including unsafe-eval!), disqus (spyware and malware) and analytics (data collection and tracking) are part of the CSP whitelist? Is this somehow related to the commercial hackmd offering?

**Comment by davidmehren** [comment]
We inherited the CSP from HackMD and didn't bother revisiting it yet 😅

I don't know why Yahoo is in there (and git blame is not really helpful). It might be because it is/was used on the features page.
Disqus and Google Analytics are optional features which can be enabled per-note via [YAML Metadata](https://demo.hedgedoc.org/yaml-metadata#GA).

You can disable Disqus and GA with the `csp.addDisqus` and `csp.addGoogleAnalytics` config options or define a fully custom CSP with `csp.directives`. See the [computeDirectives](https://github.com/hedgedoc/hedgedoc/blob/d0547a033758df86caa338a94af8e66329281720/lib/csp.js#L39) function.

**Comment by dbrgn** [comment]
Ah, thanks for the information!

I'd suggest removing all potentially privacy-invading services from the rules by default, and let the user opt-in if they're needed.

**Comment by dns2utf8** [comment]
I would love a policy like this:
```
add_header content-security-policy "default-src 'self'; img-src *;  style-src 'self' 'unsafe-inline'; object-src 'none'; media-src *; child-src *; connect-src 'self' wss://$host; report-uri https://csp.estada.ch/report" always
```
For the transition I assume a policy like this could work for most people:
```
add_header content-security-policy "default-src 'self'; script-src 'self' 'unsafe-eval'; img-src *;  style-src 'self' 'unsafe-inline'; font-src 'self' data: ; object-src 'none'; media-src *; child-src *; connect-src *; report-uri https://csp.estada.ch/report" always
```
The `connect-src: 'self'` sadly does not allow `wss://` so I think it would be very nice of hedgedoc to fill in the `$host` in the `connect-src`

**Comment by SISheogorath** [comment]
The yahooapi entry originates from an embedding in the demo page. However since its introduction, the world changed and it disappeared by now. So we can remove it as well 🎉 

About Google Analytics and disqus: The reasons why they are on by default are simple: No breaking changes in a 1.x release. They are required for existing features to function and those features were there before CSPs, as result, they are allowed by default, but can be disabled if you distrust them, since the latter is not a breaking change, but a new feature, it was possible to introduce it in 1.x.

**Comment by davidmehren** [comment]
So can we change *anything* in the default CSP in 1.x?
Somebody might use a Yahoo-thing (Yahoo *does* still exist, right?) which would get broken by us removing `query.yahooapis.com`.

**Comment by SISheogorath** [comment]
The yahoo part seems to be disappeared when we checked the features page. I think it got lost when removing one of the slide embeddings that were broken for multiple versions. So we should be able to remove it from the CSP, then see who complains.

**Comment by ErikMichelson** [comment]
As @SISheogorath already mentioned, we can't get rid of the `unsafe-eval`. The yahoo-thing should be removed with  #1088.

Btw: The `script-loader` that currently uses the evil-eval actually has a "not maintained, do not use it!"-warning. They suggest using `raw-loader` instead. It might be an idea to change that (in another PR) too.

**Comment by davidmehren** [comment]
#1088 has been merged.
Unfortunately, migrating to raw-loader won't help with removing `eval()`, as the [migration](https://github.com/webpack-contrib/script-loader) looks like this:
```diff
- import('script-loader!someScript.js')
+ import('raw-loader!someScript.js').then(rawModule => eval.call(null, rawModule.default))
```
So removing Yahoo is really all we can change in 1.x.
