### ISSUE TITLE
embedded URLs are dead in export unless they beginn with `https://`

### ISSUE THREAD

**Issue by moedn** [hedgedoc/hedgedoc#939]
First of all: **Thousand thanks for this amazing piece of software!** We use HedgeDoc all the time for internal and external collaboration. It inspired us to the massive use of markdown for anything, it's a great starter if document should later live on git and a I never had the opportunity to **thank you** for all this work. So: Thank you :)

Now the bug:

**Description**
As in title: URLs are dead in export unless they beginn with `https://`

We have a self-hosted instance on <https://pad2.opensourceecology.de/>. When embedded links won't start with `https` the exported link will just point to <https://pad2.opensourceecology.de/>. This is however not the case, if URLs are not embedded:

|source (input)|export (output)|
|---|---|
|`[buggy reference](doi.org/10.1016/j.techfore.2020.119986)`|`[buggy reference](https://pad2.opensourceecology.de/)`|
|`[working reference](https://doi.org/10.1016/j.techfore.2020.119986)`|`[working reference](https://doi.org/10.1016/j.techfore.2020.119986)`|
|`doi.org/10.1016/j.techfore.2020.119986`|`doi.org/10.1016/j.techfore.2020.119986`|
|`<doi.org/10.1016/j.techfore.2020.119986>`|`<doi.org/10.1016/j.techfore.2020.119986>`|

Or see [this](https://pad2.opensourceecology.de/cSM-9AKFQm2T_Zivh0Z5GQ?both) as an illustration.

**Expected behavior**

Embedded URL remains unchanged, even if `https://` in the input is omitted.

**Config**

HedgeDoc v1.7.2

**Comment by aisbergg** [comment]
To clarify this, he refers to inline links (`[LINK](URI)`) and how they are converted to HTML links. When _URI_ conforms the URI definition `scheme:[//authority]path[?query][#fragment]`, then a link such as `<a href="scheme:[//authority]path[?query][#fragment]">link</a>` gets created, when the scheme is omitted, it is usually an indication of a local, relative resource `<a href="/foo.jpg">link</a>`.

In Hedgedoc there is a small issue regarding the creation of relative links, here is an Example:

- `[link](/foo)`
    - Expected Behavior: `<a href="/foo">link</a>`
    - Actual Result: `<a href="/foo">link</a>` ✔️
    - What Github does: [link](/foo)

- `[link](foo)`
    - Expected Behavior: `<a href="foo">link</a>`
    - Actual Result: `<a href="">link</a>` ✖️
    - What Github does: [link](foo)

**Comment by mrdrogdrog** [comment]
Okay. Let's take this apart.
HedgeDoc 1 has a XSS-Protection that filters URIs. It seems like this XSS-Protection also filters relative links. If a URI looks "suspicious" then it won't appear in the output.

HedgeDoc 1 also uses a base-url header tag which extends relative URIs to absolute URIs. This is used to build the correct path for resource files but it used on EVERY relative uri.

With these two information in mind it's pretty easy to understand why these bugs appear:

`[buggy reference](doi.org/10.1016/j.techfore.2020.119986)` results in `[buggy reference](https://pad2.opensourceecology.de/)` because the URI is treated as relative, got replaced with an empty URI by the XSS protection and then extended with the base url.

`[working reference](https://doi.org/10.1016/j.techfore.2020.119986)` results in `[working reference](https://doi.org/10.1016/j.techfore.2020.119986)` because it's an absolute URI. No need to extend it with the base url or to filter it away.

Now comes another tricky part: Markdown links and plain links are treated by different (built in) plugins of the markdown library. While markdown links are used as they are given, the plain text links are extended with a scheme if omited. `doi.org/10.1016/j.techfore.2020.119986` gets extended to `http://doi.org/10.1016/j.techfore.2020.119986` which is an absolute URI.

**Comment by mrdrogdrog** [comment]
The HedgeDoc 1 code base is untested and a huge mess. I'm not sure if we should mess with the XSS Protection because it's unclear which side effects or security holes could open up.

**Comment by mrdrogdrog** [comment]
We decided to not change this behaviour in HedgeDoc 1.
