### ISSUE TITLE
Mindmap Support

### ISSUE THREAD

**Issue by thmo** [hedgedoc/hedgedoc#978]
Would be cool to get support for mindmaps.

https://github.com/hackmdio/codimd/issues/1407 mentions two possible implementations for markmap:

- https://github.com/gera2ld/markmap-lib
- https://github.com/dundalek/markmap

In https://github.com/hackmdio/codimd/pull/1483, CodiMD merged support for the first one.

**Comment by ErikMichelson** [comment]
The in-development version 2.0 already has markmap integrated.

See the frontend-demo over here: https://ui-test.hedgedoc.org/n/features#markmap
(Please note that there's no backend connected at the moment, local changes won't be saved.)

**Comment by ValentinDrean** [comment]
> See the frontend-demo over here: https://ui-test.hedgedoc.org/n/features#markmap

This link is dead and demo.hedgedoc.org gives 404.

╮(─▽─)╭

**Comment by ErikMichelson** [comment]
The link for the UI test has changed since then to https://hedgedoc.dev

I cannot reproduce a 404 error on demo.hedgedoc.org, however this instance runs the nightly 1.x code not the 2.0 tests.

However, during development we noticed that the markmap-parser is not suitable for us and requires a replacement. We're tracking this in #2926.

**Comment by rafacouto** [comment]
> The in-development version 2.0 already has markmap integrated.

Tested in 2.0 and seems good :)

![image](https://github.com/user-attachments/assets/1fd5b643-42a3-43f0-9a4a-720f1f1ce141)
