### ISSUE TITLE
Explore Page

### ISSUE THREAD

**Issue by davidmehren** [hedgedoc/hedgedoc#994]
**Idea:**
Create an "explore" page.  
It would show all notes the current user has access to on the instance and provide options to filter for owner and tags.

Inspired by e.g. [the GitLab explore pgae](https://gitlab.com/explore)

**Use-cases:**
- List all notes a user can access https://github.com/hedgedoc/hedgedoc/issues/455
- List notes that another user owns https://github.com/hedgedoc/hedgedoc/issues/54
- List all notes with a given tag https://github.com/hedgedoc/hedgedoc/issues/558

**Details already discussed:**
- Global option: Enable explore page?
- Global option: Show explore page only to logged-in users?
- Option per note: Show note in explore page?
    - Only if the note is shared with "everyone" or "only logged in users"
    - Admin can configure the default
    
**Open questions:**
none

**Comment by rastapopougros** [comment]
Perfect solution, it will solves all, thanks :)

**Comment by mrdrogdrog** [comment]
Interesting idea, but shouldn't this issue be part of github.com/hedgedoc/react-client?

**Comment by davidmehren** [comment]
I'd first discuss the feature here, if we have defined the scope we can create actionable issues here and in the frontend repo.

**Comment by pinpox** [comment]
Any updates on this? An overview of all pads I can access would be awesome, I'm using hedgedoc collaboratively and this is often a source of confusion.

**Comment by mrdrogdrog** [comment]
This will be a feature in HedgeDoc 2. Right now we're waiting for some design drafts.

**Comment by mrdrogdrog** [comment]
After some internal discussions and mock ups we decided on the following results:
- The explore page will replace the history page completly. 
- It will always be available for logged-in-users and guests
- It will show owned notes, notes that are shared with me and recently visited notes.
- There will be filter and search options.

**Comment by pinpox** [comment]
Any update on this? is the explore page or "View all notes" coming in near future?

**Comment by MichaelTunnell** [comment]
I have been using Hedgedoc for years now and it has been a great experience in every way except this. For a very long time, this didnt really bother me because everything else is so good but recently I realized that i personally have over 600 notes in my user history and that doesnt count the notes sent to me when not logged in. Plus all the other users who are on the instance and I think it is safe to say there are thousands of notes. I would really like the ability to see the full list of notes (as the admin) and possibly the ability to purge notes with filtering or something.

**Comment by tzwenn** [comment]
I came across the need for a global index search multiple times. While still loving to see this with HedgeDoc 2, I hacked together an external tool to do this with the current HedgeDoc 1 we have at hand: https://github.com/Chaostreff-Potsdam/hedgedoc-tag-searcher

The idea is, that users need to explicitly mark their pads with `plzidx` to be discoverable by the index feature. We need this since we found in our organization many pads formed a kind of wiki. But newjoiners didn't find the "start" pages anymore. Maybe it helps your case too.

Note: It is very WiP, has a hacky codebase (I'm not a web guy 🙈) and will break with HedgeDoc 2. But then, with v2 realease, we don't need this anymore. 🎉🤞
